version: "3.8"
services:
  jest:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: test-container
    volumes:
      - ./JS_Examples/:/usr/share/unit_test
    command: npm test
