# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome(executable_path="C:\driver\chromedriver")
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://www.tutorialspoint.com/selenium/selenium_automation_practice.htm")
    self.driver.set_window_size(1050, 700)
    self.driver.find_element(By.NAME, "firstname").click()
    self.driver.find_element(By.NAME, "firstname").send_keys("Juan Esteban")
    self.driver.find_element(By.NAME, "lastname").click()
    self.driver.find_element(By.NAME, "lastname").send_keys("Acevedo Carmona")
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) span:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, "span:nth-child(5) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) input").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) input").send_keys("03/08/200")
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(6) span:nth-child(2) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(8) span:nth-child(3) > input").click()
    self.driver.find_element(By.NAME, "continents").click()
    dropdown = self.driver.find_element(By.NAME, "continents")
    dropdown.find_element(By.XPATH, "//option[. = 'Australia']").click()
    # dropdown = self.driver.find_element(By.NAME, "selenium_commands")
    # dropdown.find_element(By.XPATH, "//option[. = 'Switch Commands']").click()
  
